version: "3.7"
services:
  app:
    build:
      args:
        user: ${ENV_USER}
        uid: ${ENV_UID}
      context: ./
      dockerfile: Dockerfile
    image: cpapp
    container_name: cpapp-php
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - cpappnet

  db:
    image: mysql:5.7
    container_name: cpapp-db
    restart: unless-stopped
    ports:
      - 33072:3306
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - cpappnet

  nginx:
    image: nginx:alpine
    container_name: cpapp-nginx
    restart: unless-stopped
    expose:
      - "7002"
    ports:
      - 7002:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - cpappnet

  redis:
    image: redis
    container_name: cpapp-redis
    command: redis-server --requirepass Redis2019!
    ports:
      - "6379:6379"
    networks:
      - cpappnet
networks:
  cpappnet:
    driver: bridge